import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import { TRPCReactProvider } from "@rn-solito-test/trpc/client";
import { AppProvider } from "@rn-solito-test/app/app-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<AppProvider>
				<TRPCReactProvider headers={headers()}>
					<body className={inter.className}>{children}</body>
				</TRPCReactProvider>
			</AppProvider>
		</html>
	);
}
